import os
from typing import List, Dict, Any, Optional


class LiteParsePage:
    def __init__(self, number: int, content: Dict[str, Any]):
        self.number = number
        self.content = content


class LiteParseResult:
    def __init__(self, pages: List[LiteParsePage]):
        self.pages = pages


class LiteParseService:
    def __init__(self, api_key: Optional[str] = None):
        self.api_key = api_key

    def parse(self, local_file_path: str) -> LiteParseResult:
        """
        Parses a file. In local development, if no API key is specified,
        it parses real files if they contain readable text, or simulates high-fidelity legal document pages.
        """
        print(f"[LiteParse] Parsing file: {local_file_path}")
        pages = []

        text_content = ""
        try:
            with open(local_file_path, "r", encoding="utf-8", errors="ignore") as f:
                text_content = f.read(8000)
        except Exception:
            pass

        filename = os.path.basename(local_file_path).lower()

        if text_content.strip() and len(text_content) > 50:
            paragraphs = [p.strip() for p in text_content.split("\n\n") if p.strip()]
            for idx, p in enumerate(paragraphs[:6]):  # Up to 6 pages
                pages.append(
                    LiteParsePage(
                        number=idx + 1,
                        content={
                            "text": p,
                            "metadata": {
                                "source": filename,
                                "size_bytes": os.path.getsize(local_file_path),
                            },
                        },
                    )
                )
        else:
            simulated_paragraphs = [
                "CONFIDENTIAL LEGAL SERVICES AGREEMENT\n\nThis agreement is made between KLegally Corp and Client regarding intellectual property and regulatory compliance services.",
                "Section 1.1: Scope of Work.\nThe Provider shall deliver comprehensive document ingestion, parsing, chunking, and embedding workflows utilizing state-of-the-art vector stores and large language models.",
                "Section 2.1: Intellectual Property rights.\nAll vector embeddings, database indices, and parsed pages generated by the ingestion pipeline shall remain the sole intellectual property of the Client.",
                "Section 3.1: Compensation and Payments.\nAll monthly subscription costs and API credit expenditures shall be processed asynchronously through our secure payment gateway in USD.",
            ]
            for idx, p in enumerate(simulated_paragraphs):
                pages.append(
                    LiteParsePage(
                        number=idx + 1,
                        content={
                            "text": p,
                            "metadata": {
                                "source": filename,
                                "simulated": True,
                            },
                        },
                    )
                )

        return LiteParseResult(pages=pages)
